name: Demo

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  timeout_job:
    runs-on: ubuntu-latest

    steps:
    - name: Run Command
      run: |
        echo "Running some commands..."
        sleep 60